// TaxLens — Onboarding wizard constants

export const US_STATES = [
  { value: "AL", label: "Alabama" }, { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" }, { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" }, { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" }, { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" }, { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" }, { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" }, { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" }, { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" }, { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" }, { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" }, { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" }, { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" }, { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" }, { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" }, { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" }, { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" }, { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" }, { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" }, { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" }, { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" }, { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" }, { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" }, { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" }, { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" }, { value: "WY", label: "Wyoming" },
  { value: "DC", label: "District of Columbia" },
] as const

export const TOP_NAICS_CODES = [
  { code: "711510", label: "Independent Artists, Writers, and Performers" },
  { code: "541511", label: "Custom Computer Programming Services" },
  { code: "541512", label: "Computer Systems Design Services" },
  { code: "541610", label: "Management Consulting Services" },
  { code: "541810", label: "Advertising Agencies" },
  { code: "541820", label: "Public Relations Agencies" },
  { code: "541910", label: "Marketing Research and Public Opinion Polling" },
  { code: "541990", label: "Other Professional, Scientific, and Technical Services" },
  { code: "519130", label: "Internet Publishing and Broadcasting" },
  { code: "512110", label: "Motion Picture and Video Production" },
  { code: "512191", label: "Teleproduction and Other Post-Production Services" },
  { code: "512240", label: "Sound Recording Studios" },
  { code: "711130", label: "Musical Groups and Artists" },
  { code: "531210", label: "Offices of Real Estate Agents and Brokers" },
  { code: "524210", label: "Insurance Agencies and Brokerages" },
  { code: "611699", label: "All Other Miscellaneous Schools and Instruction" },
  { code: "621111", label: "Offices of Physicians (Except Mental Health)" },
  { code: "621320", label: "Offices of Optometrists" },
  { code: "621330", label: "Offices of Mental Health Practitioners" },
  { code: "621340", label: "Physical, Occupational, and Speech Therapy Offices" },
  { code: "621399", label: "Other Offices of Health Practitioners" },
  { code: "812111", label: "Barber Shops" },
  { code: "812112", label: "Beauty Salons" },
  { code: "812113", label: "Nail Salons" },
  { code: "812199", label: "Other Personal Care Services" },
  { code: "238100", label: "Foundation, Structure, and Building Exterior Contractors" },
  { code: "238210", label: "Electrical Contractors" },
  { code: "238220", label: "Plumbing, Heating, and Air-Conditioning Contractors" },
  { code: "238310", label: "Drywall and Insulation Contractors" },
  { code: "236220", label: "Commercial and Institutional Building Construction" },
  { code: "484110", label: "General Freight Trucking, Local" },
  { code: "484121", label: "General Freight Trucking, Long-Distance" },
  { code: "492110", label: "Couriers and Express Delivery Services" },
  { code: "454110", label: "Electronic Shopping and Mail-Order Houses" },
  { code: "454390", label: "Other Direct Selling Establishments" },
  { code: "453220", label: "Gift, Novelty, and Souvenir Stores" },
  { code: "722511", label: "Full-Service Restaurants" },
  { code: "722513", label: "Limited-Service Restaurants" },
  { code: "561410", label: "Document Preparation Services" },
  { code: "561730", label: "Landscaping Services" },
  { code: "561790", label: "Other Services to Buildings and Dwellings" },
  { code: "811111", label: "General Automotive Repair" },
  { code: "511130", label: "Book Publishers" },
  { code: "519190", label: "All Other Information Services" },
  { code: "541700", label: "Scientific Research and Development Services" },
  { code: "561499", label: "Other Business Support Services" },
  { code: "561431", label: "Private Mail Centers" },
  { code: "813211", label: "Grantmaking Foundations" },
  { code: "721110", label: "Hotels and Motels" },
  { code: "OTHER", label: "Other — enter code manually" },
] as const

export const REVENUE_STREAMS = [
  { value: "services", label: "Services (consulting, coaching, freelance)" },
  { value: "physical_products", label: "Physical Products" },
  { value: "digital_products", label: "Digital Products (courses, templates, downloads)" },
  { value: "ad_revenue", label: "Ad Revenue (YouTube, blog, podcast)" },
  { value: "brand_deals", label: "Brand Deals / Sponsorships" },
  { value: "affiliate", label: "Affiliate Commissions" },
  { value: "subscriptions", label: "Subscriptions / Memberships" },
  { value: "gifts_pr", label: "Gifts / PR (product gifted for review)" },
] as const

export const KNOWN_ENTITY_KINDS = [
  { value: "PERSON_PERSONAL", label: "Personal — family / household (Zelle/Venmo = personal transfer)" },
  { value: "PERSON_CONTRACTOR", label: "Contractor / talent (≥$600 triggers 1099-NEC tracking)" },
  { value: "PERSON_CLIENT", label: "Client (deposit from this person = business income)" },
  { value: "PATTERN_EXCLUDED", label: "Excluded pattern (e.g. HSMCA donations, personal loan)" },
  { value: "PATTERN_INCOME", label: "Income pattern (e.g. TheKnot, PayPal Business deposits)" },
] as const

export const TRANSACTION_CODES = [
  { value: "WRITE_OFF", label: "Write-off (deductible business expense)" },
  { value: "WRITE_OFF_TRAVEL", label: "Write-off — Travel" },
  { value: "WRITE_OFF_COGS", label: "Write-off — COGS" },
  { value: "MEALS_50", label: "Meals 50% deductible" },
  { value: "MEALS_100", label: "Meals 100% deductible" },
  { value: "GRAY", label: "Gray — needs review" },
  { value: "PERSONAL", label: "Personal — not deductible" },
  { value: "TRANSFER", label: "Transfer between own accounts" },
  { value: "PAYMENT", label: "Credit card payment" },
  { value: "BIZ_INCOME", label: "Business income" },
] as const

export const INCOME_CATEGORIES = [
  { value: "direct_bank", label: "Direct bank deposit / ACH" },
  { value: "stripe", label: "Stripe" },
  { value: "square", label: "Square" },
  { value: "paypal_business", label: "PayPal Business" },
  { value: "zelle_business", label: "Zelle (business)" },
  { value: "venmo_business", label: "Venmo (business)" },
  { value: "1099_platform", label: "1099 Platform (TheKnot, Bark, etc.)" },
  { value: "check", label: "Check" },
  { value: "cash", label: "Cash" },
  { value: "other", label: "Other" },
] as const
